% This is an autogenerated sample test for file practika1.mlx
classdef testpractika1 < matlab.unittest.TestCase
    
    properties (TestParameter)
        testParameter1 = struct("scalar",1,"vector",[1 1]);
    end

    methods (Test)

        function test_practika1(testCase)
            % Exercise the script practika1
            practika1;
        end
        
        function test1(testCase)
            
        end
    end
    
    methods (TestMethodSetup)
        
        function methodSetup1(testCase)
            % Set up fresh state for each test.
            
            % Tear down with testCase.addTeardown.
        end
        
    end
    
    methods (TestClassSetup)
        
        function classSetup1(testCase)
            % Set up shared state for all tests.
            
            % Tear down with testCase.addTeardown.
        end
        
    end
end